---
# defaults file for jupyterworkspace
delete_event: false
name: "{{ meta.name | default('tensorflow') }}"

resources:
  memory: 2Gi
  cpu: 1
  volume_size: 2Gi
object_storage:
  endpoint: http://ceph:8080
  secret_access_key: ""
  access_key_id: ""
jupyter_image: "quay.io/vpavlin/jupyter-notebook-tensorflow"
openshift_auth: true
can_edit_namespace: false