---
# defaults file for jupyterworkspace
name: "{{ meta.name | default('jupyter-workspace') }}"

resources:
  memory: 2Gi
  cpu: 1
  volumeSize: 2Gi
objectStorage:
  s3Endpoint: http://ceph:8080
  secretAccessKey: ""
  accessKeyId: ""
jupyterImage: "quay.io/vpavlin/jupyter-notebook-tensorflow"
openshiftAuth: true
canEditNamespace: false