apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jupyterworkspaces.opendatahub.io
spec:
  group: opendatahub.io
  names:
    kind: JupyterWorkspace
    listKind: JupyterWorkspaceList
    plural: jupyterworkspaces
    singular: jupyterworkspace
    shortNames:
    - jw
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
