---
# tasks file for jupyterworkspace
- name: 'Configure Jupyter Workspace {{ name }}'
  k8s:
    state: present
    definition: "{{ lookup('template', item.name) }}"
  with_items:
    - name: "configMap.json.j2"
    - name: "serviceAccount.json.j2"
    - name: "persistentVolumeClaim.json.j2"
    - name: "deploymentConfig.json.j2"
    - name: "service.json.j2"
    - name: "route.json.j2"

- name: 'Set Role Binding for Jupyter Workspace {{ name }}'
  k8s:
    state: present
    definition: "{{ lookup('template', item.name) }}"
  when: can_edit_namespace
  with_items:
    - name: "roleBinding.json.j2"